# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cons.xdc

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# Block Designs: bd/dopmidsem/dopmidsem.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem || ORIG_REF_NAME==dopmidsem} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_IF_ID_0_0/dopmidsem_IF_ID_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_IF_ID_0_0 || ORIG_REF_NAME==dopmidsem_IF_ID_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_ID_0_0/dopmidsem_ID_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_ID_0_0 || ORIG_REF_NAME==dopmidsem_ID_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_ControlUnit_0_0/dopmidsem_ControlUnit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_ControlUnit_0_0 || ORIG_REF_NAME==dopmidsem_ControlUnit_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_ControlUnit_1_0/dopmidsem_ControlUnit_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_ControlUnit_1_0 || ORIG_REF_NAME==dopmidsem_ControlUnit_1_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_ID_RN_0_0/dopmidsem_ID_RN_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_ID_RN_0_0 || ORIG_REF_NAME==dopmidsem_ID_RN_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_ROB_0_0/dopmidsem_ROB_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_ROB_0_0 || ORIG_REF_NAME==dopmidsem_ROB_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_RAT_0_0/dopmidsem_RAT_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_RAT_0_0 || ORIG_REF_NAME==dopmidsem_RAT_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_RN_0_0/dopmidsem_RN_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_RN_0_0 || ORIG_REF_NAME==dopmidsem_RN_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_RN_IS_0_0/dopmidsem_RN_IS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_RN_IS_0_0 || ORIG_REF_NAME==dopmidsem_RN_IS_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_IQ_0_0/dopmidsem_IQ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_IQ_0_0 || ORIG_REF_NAME==dopmidsem_IQ_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_RegFile_0_0/dopmidsem_RegFile_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_RegFile_0_0 || ORIG_REF_NAME==dopmidsem_RegFile_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_URS_0_0/dopmidsem_URS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_URS_0_0 || ORIG_REF_NAME==dopmidsem_URS_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_LSQ_0_0/dopmidsem_LSQ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_LSQ_0_0 || ORIG_REF_NAME==dopmidsem_LSQ_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_BC_0_0/dopmidsem_BC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_BC_0_0 || ORIG_REF_NAME==dopmidsem_BC_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_DataMem_0_0/dopmidsem_DataMem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_DataMem_0_0 || ORIG_REF_NAME==dopmidsem_DataMem_0_0} -quiet] -quiet

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_BC_WB_0_0/dopmidsem_BC_WB_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_BC_WB_0_0 || ORIG_REF_NAME==dopmidsem_BC_WB_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_CM_0_0/dopmidsem_CM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_CM_0_0 || ORIG_REF_NAME==dopmidsem_CM_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_EX_0_0/dopmidsem_EX_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_EX_0_0 || ORIG_REF_NAME==dopmidsem_EX_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_EX_ALU_0_0/dopmidsem_EX_ALU_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_EX_ALU_0_0 || ORIG_REF_NAME==dopmidsem_EX_ALU_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_EX_ALU_1_0/dopmidsem_EX_ALU_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_EX_ALU_1_0 || ORIG_REF_NAME==dopmidsem_EX_ALU_1_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_EX_BC_0_0/dopmidsem_EX_BC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_EX_BC_0_0 || ORIG_REF_NAME==dopmidsem_EX_BC_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_IS_EX_0_0/dopmidsem_IS_EX_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_IS_EX_0_0 || ORIG_REF_NAME==dopmidsem_IS_EX_0_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_system_ila_0_1/dopmidsem_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_system_ila_0_1 || ORIG_REF_NAME==dopmidsem_system_ila_0_1} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_InstrMem_0_3/dopmidsem_InstrMem_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_InstrMem_0_3 || ORIG_REF_NAME==dopmidsem_InstrMem_0_3} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: bd/dopmidsem/ip/dopmidsem_IF_wrapper_0_0/dopmidsem_IF_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dopmidsem_IF_wrapper_0_0 || ORIG_REF_NAME==dopmidsem_IF_wrapper_0_0} -quiet] -quiet

# XDC: /home/govind/RISCV_5/RISCV_5.gen/sources_1/bd/dopmidsem/dopmidsem_ooc.xdc
