# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/govind/RISCV_5/RISCV_5.srcs/sources_1/bd/dopmidsem/ip/dopmidsem_DataMem_0_0/dopmidsem_DataMem_0_0.xci
# IP: The module: 'dopmidsem_DataMem_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/govind/RISCV_5/RISCV_5.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# XDC: /home/govind/RISCV_5/RISCV_5.gen/sources_1/bd/dopmidsem/ip/dopmidsem_DataMem_0_0/dopmidsem_DataMem_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dopmidsem_DataMem_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/govind/RISCV_5/RISCV_5.srcs/sources_1/bd/dopmidsem/ip/dopmidsem_DataMem_0_0/dopmidsem_DataMem_0_0.xci
# IP: The module: 'dopmidsem_DataMem_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/govind/RISCV_5/RISCV_5.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# XDC: /home/govind/RISCV_5/RISCV_5.gen/sources_1/bd/dopmidsem/ip/dopmidsem_DataMem_0_0/dopmidsem_DataMem_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dopmidsem_DataMem_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
