# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/govind/RISCV_5/RISCV_5.srcs/sources_1/bd/dopmidsem/ip/dopmidsem_InstrMem_0_3/dopmidsem_InstrMem_0_3.xci
# IP: The module: 'dopmidsem_InstrMem_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/govind/RISCV_5/RISCV_5.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: /home/govind/RISCV_5/RISCV_5.gen/sources_1/bd/dopmidsem/ip/dopmidsem_InstrMem_0_3/dopmidsem_InstrMem_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dopmidsem_InstrMem_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/govind/RISCV_5/RISCV_5.srcs/sources_1/bd/dopmidsem/ip/dopmidsem_InstrMem_0_3/dopmidsem_InstrMem_0_3.xci
# IP: The module: 'dopmidsem_InstrMem_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/govind/RISCV_5/RISCV_5.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: /home/govind/RISCV_5/RISCV_5.gen/sources_1/bd/dopmidsem/ip/dopmidsem_InstrMem_0_3/dopmidsem_InstrMem_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dopmidsem_InstrMem_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
